package com.example.presentation.navigation

sealed class Screen(val route: String) {
    data object Splash : Screen("splash")
    data object Login : Screen("login")
    data object OnboardingWalkthrough : Screen("onboarding_walkthrough")
    data object PermissionSetup : Screen("permission_setup")
    data object BatterySetup : Screen("battery_setup")
    data object AccessibilitySetup : Screen("accessibility_setup")
    data object Dashboard : Screen("dashboard")
    data object Assistant : Screen("assistant")
    data object LiveVision : Screen("live_vision")
    data object Chat : Screen("chat")
    data object Triggers : Screen("triggers")
    data object CommandHistory : Screen("history")
    data object Profile : Screen("profile")
    data object Settings : Screen("settings")
    data object Permissions : Screen("permissions")
    data object IntelligenceModes : Screen("intelligence_modes")
    data object VoiceAndAiModels : Screen("voice_and_ai_models")
    data object OrbCustomization : Screen("orb_customization")
    data object ApiAndCloudSettings : Screen("api_and_cloud_settings")
    data object Connectors : Screen("connectors")
    data object PcConnect : Screen("pc_connect")
    data object LicenseActivation : Screen("license_activation")
    data object Subscription : Screen("subscription")
    data object VoiceAuthentication : Screen("voice_authentication")
    data object VoiceGuardian : Screen("voice_guardian")
    data object BatchUpdate : Screen("batch_update")
    data object PrivacyPolicy : Screen("privacy_policy")
    data object AutomotiveDiagnostics : Screen("automotive_diagnostics")
    data object SecurityShield : Screen("security_shield")
    data object VoiceConsole : Screen("voice_console")
}

